### ISSUE TITLE
Create a type for the query plan response

### ISSUE THREAD

**Issue by tibo-mllr** [tibo-mllr/activeviam-projet#24]

**Comment by carlrizk** [comment]
You can find a swagger page for the server REST API by going to `<server URL>/activeviam/swagger-ui/index.html`. 

What interests you are the GET and POST versions of the API:
- https://activepivot-ranch.activeviam.com:6100/activeviam/swagger-ui/index.html#/queries-rest-service-controller/mdxQueryPlan
- https://activepivot-ranch.activeviam.com:6100/activeviam/swagger-ui/index.html#/queries-rest-service-controller/mdxQueryPlan_1

This can help you build your types as there is a schema available. The schema might not be exhaustive though.
Notice that the GET version can take a `asSummary` query parameter which can help you find the information shown in the `Summary` tab of the old too.
