### ISSUE TITLE
Report for the 20th of december

### ISSUE THREAD

**Issue by AlexandreCGithub** [tibo-mllr/activeviam-projet#43]
Report for the 20th of december to prepare the mid point. See the related mail.

> •	Le contexte de votre projet ainsi que le problème posé, que vous aurez donc reformulé.
> •	Un état des lieux ou de l'art des solutions existantes pour le problème posé.
> •	Un schéma d'ensemble avec les différents fonctions attendues. 
> •	Une analyse des points clés et une justification des choix techniques et/ou scientifiques.
> •	Une liste des tâches envisagées et l'état d'avancement
> •	Problèmes rencontrés

**Comment by AlexandreCGithub** [comment]
Created a file in the drive

**Comment by tibo-mllr** [comment]
Sent on the Teams Assignment
